app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('', include('user.urls')),
    path('', include('room.urls')),
    path('', include('reserve.urls')),
    path('', include('equipment.urls')),
    path('', include('report.urls')),
]

room/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('room/', views.room_list, name='room_list'),
    path('room/create/', views.create_room, name='create_room'),
    path('room/detail/<int:room_id>/', views.room_detail, name='room_detail'),
    path('room/update/<int:room_id>/', views.update_room, name='update_room'),
    path('room/delete/<int:room_id>/', views.delete_room, name='delete_room'),
    path('room/availability/<int:room_id>/', views.room_availability, name='room_availability'),
    path('room/events/<int:room_id>/', views.event_room_availability, name='room_event'),
    path('room/<int:room_id>/rate/', views.rate_room, name='rate_room'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room/models.py
from django.db import models
from equipment.models import Equipment
from django.contrib.auth.models import User
from django.db.models import Avg


# Create your models here.
class Room(models.Model):
    name = models.CharField(max_length=100)
    capacity = models.IntegerField()
    location = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    equipments = models.ManyToManyField(Equipment, blank=True)
    photo = models.ImageField(upload_to='room_photos', blank=True, null=True)

    def average_rating(self):
        return self.ratings.aggregate(Avg('score'))['score__avg'] or 0
    
    def __str__(self):
        return self.name


class Rating(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='ratings')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.PositiveSmallIntegerField(choices=[(i, i) for i in range(1, 6)])
    comment = models.TextField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.room.name} - {self.user.username} - {self.score}'

room/forms.py
from django import forms
from .models import Room, Rating


class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ['name', 'capacity', 'location', 'description', 'equipments', 'photo']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'capacity': forms.NumberInput(attrs={'class': 'form-control'}),
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control','rows': 3}),
            'equipments': forms.CheckboxSelectMultiple(),
            'photo': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }
        labels = {
            'name': 'Nome',
            'capacity': 'Capacidade',
            'location': 'Localização',
            'description': 'Descrição',
            'equipments': 'Equipamentos',
            'photo': 'Foto,'
        }


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ['score', 'comment']
        widgets = {
            'score': forms.Select(choices=[(i, f"{i} Estrela{'s' if i > 1 else ''}") for i in range(1, 6)]),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': 3})
        }
        labels = {
            'score': 'Nota',
            'comment': 'Comentário'
        }

room/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import JsonResponse
from .models import Room, Rating
from .forms import RoomForm, RatingForm
from reserve.models import Reserve
from django.contrib import messages


# Create your views here.
def is_admin(user):
    return user.groups.filter(name='Administradores').exists()


@login_required
def room_list(request):
    rooms = Room.objects.all()
    return render(request, 'room_list.html', {'rooms': rooms})


@login_required
def room_availability(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    return render(request, 'room_availability.html', {'room': room})


@login_required
def event_room_availability(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    reserves = Reserve.objects.filter(room=room)
        
    eventos = []
    for reserve in reserves:
        eventos.append({
            'title': f"Reservado: {reserve.user.username}",
            'start': f"{reserve.date}T{reserve.start_time}",
            'end': f"{reserve.date}T{reserve.end_time}",
            'color': 'red',
        })
    return JsonResponse(eventos, safe=False)
       

@login_required
@user_passes_test(is_admin)
def create_room(request):
    if request.method == 'POST':
        form = RoomForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('room_list')
    else:
        form = RoomForm()
    return render(request, 'room_create.html', {'form': form})


@login_required
def room_detail(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    ratings = room.ratings.all()
    context = {
        'room': room,
        'ratings': ratings,
    }
    return render(request, 'room_detail.html', context)


@login_required
@user_passes_test(is_admin)
def update_room(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    if request.method == 'POST':
        form = RoomForm(request.POST, request.FILES, instance=room)
        if form.is_valid():
            form.save()
            return redirect('room_list')
    else:
        form = RoomForm(instance=room)
    return render(request, 'room_update.html', {'form': form})
    

@login_required
@user_passes_test(is_admin)
def delete_room(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    if request.method == 'POST':
        room.delete()
        return redirect('room_list')
    return render(request, 'room_delete.html', {'room' : room})


@login_required
def rate_room(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    if request.method == 'POST':
        form = RatingForm(request.POST)
        if form.is_valid():
            rating = form.save(commit=False)
            rating.room = room
            rating.user = request.user
            rating.save()
            messages.success(request, 'Avaliação enviada com sucesso!')
            return redirect('room_detail', room_id=room.id)
    else:
        form = RatingForm()
    
    context = {
        'room': room,
        'form': form,
    }
    return render(request, 'room_rate.html', context)

room/templates/room_availability.html
{% extends "base.html" %}

{% block content %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            fixedWeekCount: false,
            initialView: 'dayGridMonth',
            locale: 'pt-br',
            headerToolbar: {
                left: 'prev,next today',
                center: 'title',
                right: 'dayGridMonth,timeGridWeek,timeGridDay'
            },
            events: '/room/events/{{ room.id }}/',
            eventClick: function (info) {
                alert('Detalhes da reserva:\n' +
                    'Reservado por: ' + info.event.title + '\n' +
                    'Início: ' + info.event.start.toLocaleString() + '\n' +
                    'Fim: ' + info.event.end.toLocaleString());
            },
            slotMinTime: "08:00:00",
            slotMaxTime: "20:00:00",
            nowIndicator: true,
            editable: false,
            selectable: false
        });

        calendar.render();
    });
</script>

<div class="container">
    <h2>Disponibilidade da Sala: {{ room.name }}</h2>
    <div id="calendar"></div>
</div>

{% endblock %}

room/templates/room_create.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0">Adicionar Sala</h4>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <p><label for="name">Nome da Sala:</label>
                            {{ form.name }}</p>
                        </div>
                        <div class="form-group">
                            <p><label for="capacity">Capacidade:</label>
                                {{ form.capacity }}</p>
                        </div>
                        <div class="form-group">
                            <p><label for="location">Localização:</label>
                            {{ form.location }}</p>
                        </div>
                        <div class="form-group">
                            <p><label for="equipments">Equipamentos:</label>
                            {{ form.equipments }}</p>
                        </div>
                        <div class="form-group">
                            <p><label for="photo">Foto da Sala:</label>
                            {{ form.photo }}</p>
                        </div>
                        <button type="submit" class="btn btn-success btn-block">Salvar Sala</button>
                        <a href="{% url 'room_list' %}" class="btn btn-secondary ">
                            Cancelar e Voltar para a Lista de Salas</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

room/templates/room_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2>Excluir Sala</h2>
    <p>Tem certeza que deseja excluir a sala <strong>{{ room.name }}</strong>?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Excluir</button>
        <a href="{% url 'room_list' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

room/templates/room_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="alert alert-info">
        <h4>Sala: {{ room.name }}</h4>
    </div>
    
    <div class="card mb-4">
        <div class="row card-body">
            <div class="col-md-8">
                <p><strong>Capacidade:</strong> {{ room.capacity }} pessoas</p>
                <p><strong>Localização:</strong> {{ room.location }}</p>
                <p><strong>Equipamentos:</strong></p>
                <ul>
                    {% for equipment in room.equipments.all %}
                        <li>{{ equipment.name }}</li>
                    {% empty %}
                        <li>Sem equipamentos</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-4 text-center">
                {% if room.photo %}
                    <img src="{{ room.photo.url }}" alt="Foto da sala" class="img-fluid rounded mt-3">
                {% else %}
                    <p>Sem foto disponível.</p>
                {% endif %}
            </div>
        </div>
    </div>
    

    <div class="alert alert-info">
        <h4>Média de Avaliação: 
            <span class="badge badge-primary">{{ room.average_rating|floatformat:1 }} / 5
                <i class="bi bi-star-fill fs-6"></i>
            </span>
        </h4>
    </div>

    <h3 class="mt-4">Avaliações</h3>
    {% if ratings %}
        <ul class="list-group mb-4">
            {% for rating in ratings %}
                <li class="list-group-item">
                    <div class="d-flex justify-content-between align-items-center">
                        <strong>{{ rating.user.username }}</strong>
                        <span class="badge badge-warning">{{ rating.score }} estrelas</span>
                    </div>
                    <p class="mb-1">{{ rating.comment }}</p>
                    <small class="text-muted">{{ rating.date|date:"d/m/Y H:i" }}</small>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Esta sala ainda não possui avaliações.</p>
    {% endif %}

    <a href="{% url 'rate_room' room.id %}" class="btn btn-primary">Avaliar Sala</a>
</div>
{% endblock %}

room/templates/room_list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2>Lista de Salas</h2>
    <a href="{% url 'create_room' %}" class="btn btn-primary float-end mb-3">Criar Nova Sala</a>
    <table class="table table-striped table-bordered table-responsive">
        <thead class="table-dark">
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Capacidade</th>
                <th scope="col">Localização</th>
                <th scope="col">Descrição</th>
                <th scope="col">Equipamentos</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for room in rooms %}
            <tr>
                <td>{{ room.name }}</td>
                <td>{{ room.capacity }}</td>
                <td>{{ room.location }}</td>
                <td>{{ room.description }}</td>
                <td>{% for equipment in room.equipments.all %}{{ equipment }}, {% endfor %}</td>
                <td>
                    <a href="{% url 'room_availability' room.id %}" class="btn btn-primary btn-sm">Ver Disponibilidade</a>
                    <a href="{% url 'room_detail' room.id %}" class="btn btn-sm btn-info">Informações</a>
                    <a href="{% url 'update_room' room.id %}" class="btn btn-sm btn-warning">Editar</a>
                    <a href="{% url 'delete_room' room.id %}" class="btn btn-sm btn-danger">Excluir</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

room/templates/room_rate.html
{% extends 'base.html' %}
 
{% block content %}
<div class="container mt-5">
    <h2 class="mb-4">Avaliar Sala: {{ room.name }}</h2>

    <form method="POST" class="bg-light p-4 rounded shadow">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="id_score">Pontuação:</label>
            {{ form.score }}
        </div>

        <p><div class="form-group">
            <label for="id_comment">Comentário:</label>
            {{ form.comment }}
        </div></p>

        <button type="submit" class="btn btn-primary">Enviar Avaliação</button>
        <a href="{% url 'room_detail' room.id %}" class="btn btn-secondary ml-2">Voltar</a>
    </form>
</div>
{% endblock %}

room/templates/room_update.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2>Editar Sala</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Salvar Alterações</button>
    </form>
    <a href="{% url 'room_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar para a Lista de Salas</a>
</div>
{% endblock %}